export const SET_PAGE_HEADING = 'SET_PAGE_HEADING'
export const GET_PAGE_HEADING = 'GET_PAGE_HEADING'

export const GET_TODOS = 'GET_TODOS'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL'

export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS'
export const CLEAR_ALL_PROJECTS = 'CLEAR_ALL_PROJECTS'

export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
